name: shop2
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  hexcolor: ^3.0.1
  font_awesome_flutter: ^10.1.0
  http: ^0.13.4
  modal_progress_hud_nsn: ^0.3.0
  dio: ^4.0.6
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  shared_preferences: ^2.0.17
  bot_toast: ^4.0.2
  fluttertoast: ^8.1.2
  intl: ^0.18.0
  conditional_builder_null_safety: ^0.0.6
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.0+1
  animated_bottom_navigation_bar: ^1.1.0+1
  image_picker: ^0.8.6+1
  smooth_page_indicator: ^1.0.0+2
  google_fonts: ^4.0.3
  awesome_dialog: ^3.0.2

  # Replace splashscreen with a null-safe alternative
  flutter_native_splash: ^2.2.17

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/cart.png
  color_dark: "#121212"
  image_dark: assets/images/cart.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: amiri
      fonts:
        - asset: assets/fonts/Amiri-Italic.ttf
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-VariableFont_wght.ttf
    - family: IconBroken
      fonts:
        - asset: assets/fonts/icons.ttf
